[package]
name = "aleo-accounts"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[dependencies]
snarkos-objects = { path = "../../snarkOS/objects", version = "0.8.0" }
