[package]
name = "aleo"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[[bin]]
name = "accounts"
path = "accounts/src/main.rs"

[workspace]
members = ["accounts"]

[dependencies]
image = { version = "0.23.4" }
qrcode = { version = "0.11" }
