name: Sync

on:
  push:
    branches: [master]

jobs:
  sync:
    - name: Sync `aleo` repository
    - run: |
      curl \
      -X POST \
      -u "${{ secrets.SYNC_USERNAME }}:${{ secrets.SYNC_TOKEN }}" \
      -H "Accept: application/vnd.github.v3+json" \
      -H "Content-Type: application/json" https://api.github.com/repos/${{ secrets.SYNC_ORGANIZATION }}/${{ secrets.SYNC_APPLICATION }}/dispatches \
      -d '{"event_type": "publish"}'
