name: Sync submodules

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 24 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update modules
        run: |
          git submodule update --remote
          git add .
          git diff-index --quiet HEAD || git commit -m "Update modules"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
