name: Sync

on:
  push:
    branches: [master]

jobs:
  sync:
    - name: Sync `aleo` repository
    - run: |
      export DISPATCH_URL="https://api.github.com/repos/${{ secrets.SYNC_ORGANIZATION }}/${{ secrets.SYNC_APPLICATION }}/dispatches"
      curl -X POST -u "${{ secrets.SYNC_USERNAME }}:${{ secrets.SYNC_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/octocat/hello-world/dispatches \
        -d '{"event_type":"event_type"}'
