name: Sync

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update the Aleo documentation to reflect the latest changes
        run: |
          cd internal/parser && yarn install && yarn start
          cd ../..

      - name: Commit files
        run: |
          git add documentation/README.md
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "Updates Aleo documentation" -a

      - name: Push to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync `aleo` repository
        run: |
          curl \
            -X POST \
            -u "${{ secrets.SYNC_USERNAME }}:${{ secrets.SYNC_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ secrets.SYNC_ORGANIZATION }}/${{ secrets.SYNC_APPLICATION }}/dispatches \
            -d '{"event_type":"Synchronize"}'
          curl \
            -X POST \
            -u "${{ secrets.SYNC_USERNAME }}:${{ secrets.SYNC_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ secrets.SYNC_ORGANIZATION }}/${{ secrets.SYNC_APPLICATION_TWO }}/dispatches \
            -d '{"event_type":"Synchronize"}'
